# authservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      nodeSelector:
        pool: userpool  # Targets user pool nodes
      containers:
      - name: authservice
        image: aksdemo001.azurecr.io/auth-service:v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
# authservice-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Internal access
