# projectservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectservice
  template:
    metadata:
      labels:
        app: projectservice
    spec:
      nodeSelector:
        pool: userpool
      containers:
        - name: projectservice
          image: aksdemo001.azurecr.io/project-service:v1
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# projectservice-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: projectservice
spec:
  selector:
    app: projectservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
